services:
  db:
    image: postgres:16
    container_name: dearobjet-postgres
    environment:
      POSTGRES_DB: dearobjet
      POSTGRES_USER: dearobjet
      POSTGRES_PASSWORD: dearobjet1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
